version: '3'
tasks:
  build:
    silent: true
    aliases: [b]
    desc: build brainfuck VM for current platform
    cmds:
      - go build -v -o ./bin/brainfuckvm ./main.go

  clean:
    silent: true
    desc: clean project
    cmds:
      - rm -rf ./bin
      - go clean
