version: '3'
tasks:
  build:
    silent: true
    aliases: [b]
    desc: build all brainfuck executable tools for current platform
    cmds:
      - go build -v -o ./bin/interpreter ./cmd/interpreter/main.go
      
  test:
    silent: true
    aliases: [t]
    desc: run all tests
    cmds:
      - go test -v ./...

  clean:
    silent: true
    desc: clean project
    cmds:
      - rm -rf ./bin
      - go clean
